version: "3.8"

services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - pg-network

  kestra:
    image: ghcr.io/kestra-io/kestra:latest
    container_name: kestra
    command: server all
    depends_on:
      - "pgdatabase"
    ports:
      - "8080:8083"
    environment:
      KESTRA_DATABASE_TYPE: postgres
      KESTRA_DATABASE_POSTGRES_URL: jdbc:postgresql://pgdatabase:5432/ny_taxi
      KESTRA_DATABASE_POSTGRES_USERNAME: kestra
      KESTRA_DATABASE_POSTGRES_PASSWORD: kestra
    volumes:
      - ./kestra-data:/app/data  
    networks:
      - pg-network

networks:
  pg-network:
    name: pg-network
    driver: bridge